### ISSUE TITLE
Project `tofu` on test.pypi.org

### ISSUE THREAD

**Issue by jamadden** [shalomb/tofu#6]
Hi! I'm one of the moderators of PyPI. In https://github.com/pypa/pypi-support/issues/147 a different user is asking to be able to use the `tofu` name or test.pypi.org like they can on pypi.org. It looks like you may have earlier published a package under that name. Could you please respond to that issue? 

Thank you!

**Comment by shalomb** [comment]
`tofu` on test.pypi.org deleted.
